=== pgurdek/javafx-question-game/db/src/main/resources/pl/db/schema.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="urn:Test.Namespace"
            xmlns="urn:Test.Namespace"
            elementFormDefault="qualified"
>
    <xsd:element name="questions">
        <xsd:complexType>
            <xsd:sequence minOccurs="2" maxOccurs="10">
                <xsd:element name="question" type="question"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="question">
        <xsd:sequence>
            <xsd:element name="content" type="xsd:string"/>
            <xsd:element name="answer1" type="xsd:string"/>
            <xsd:element name="answer2" type="xsd:string"/>
            <xsd:element name="answer3" type="xsd:string"/>
            <xsd:element name="answer4" type="xsd:string"/>
            <xsd:element name="correctAnswer" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== pgurdek/javafx-question-game/db/src/test/resources/data.xml
<questions xmlns="urn:Test.Namespace"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="urn:Test.Namespace file:///D:\projects\question-game\db\src\main\resources\pl\db\schema.xsd">

    <question>
        <content>Who delivered the less famous two-hour speech that preceded Abraham Lincoln's two-minute Gettysburg Address?</content>
        <answer1>Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem </answer1>
        <answer2>DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD</answer2>
        <answer3>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</answer3>
        <answer4>1000</answer4>
        <correctAnswer>1000</correctAnswer>
    </question>

    <question>
        <content>Who delivered the less famous two-hour speech that preceded Abraham Lincoln's two-minute Gettysburg Address?</content>
        <answer1>Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem </answer1>
        <answer2>DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD</answer2>
        <answer3>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</answer3>
        <answer4>1000</answer4>
        <correctAnswer>1000</correctAnswer>
    </question>


    <question>
        <content>Who delivered the less famous two-hour speech that preceded Abraham Lincoln's two-minute Gettysburg Address?</content>
        <answer1>Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem </answer1>
        <answer2>DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD</answer2>
        <answer3>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</answer3>
        <answer4>1000</answer4>
        <correctAnswer>1000</correctAnswer>
    </question>


    <question>
        <content>Who delivered the less famous two-hour speech that preceded Abraham Lincoln's two-minute Gettysburg Address?</content>
        <answer1>Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem </answer1>
        <answer2>DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD</answer2>
        <answer3>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</answer3>
        <answer4>1000</answer4>
        <correctAnswer>1000</correctAnswer>
    </question>


    <question>
        <content>Who delivered the less famous two-hour speech that preceded Abraham Lincoln's two-minute Gettysburg Address?</content>
        <answer1>Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem </answer1>
        <answer2>DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD</answer2>
        <answer3>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</answer3>
        <answer4>1000</answer4>
        <correctAnswer>1000</correctAnswer>
    </question>


    <question>
        <content>Who delivered the less famous two-hour speech that preceded Abraham Lincoln's two-minute Gettysburg Address?</content>
        <answer1>Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem </answer1>
        <answer2>DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD</answer2>
        <answer3>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</answer3>
        <answer4>1000</answer4>
        <correctAnswer>1000</correctAnswer>
    </question>

    <question>
        <content>Who delivered the less famous two-hour speech that preceded Abraham Lincoln's two-minute Gettysburg Address?</content>
        <answer1>Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem </answer1>
        <answer2>DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD</answer2>
        <answer3>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</answer3>
        <answer4>1000</answer4>
        <correctAnswer>1000</correctAnswer>
    </question>

    <question>
        <content>Who delivered the less famous two-hour speech that preceded Abraham Lincoln's two-minute Gettysburg Address?</content>
        <answer1>Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem </answer1>
        <answer2>DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD</answer2>
        <answer3>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</answer3>
        <answer4>1000</answer4>
        <correctAnswer>1000</correctAnswer>
    </question>

    <question>
        <content>Who delivered the less famous two-hour speech that preceded Abraham Lincoln's two-minute Gettysburg Address?</content>
        <answer1>Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem Ipsum Lorem IpsumLorem IpsumLorem </answer1>
        <answer2>DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD</answer2>
        <answer3>YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY</answer3>
        <answer4>1000</answer4>
        <correctAnswer>1000</correctAnswer>
    </question>
</questions>

=== pgurdek/javafx-question-game/client/src/main/resources/data.xml
<questions xmlns="urn:questionSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="urn:questionSchema file:///D:\projects\question-game\db\src\main\resources\pl\db\schema.xsd">

    <question>
        <content></content>
        <answer1></answer1>
        <answer2></answer2>
        <answer3></answer3>
        <answer4></answer4>
        <correctAnswer></correctAnswer>
    </question>
    <question>
        <content>2+5</content>
        <answer1>4</answer1>
        <answer2>1</answer2>
        <answer3>2</answer3>
        <answer4>7</answer4>
        <correctAnswer>4</correctAnswer>
    </question>
    <question>
        <content>2+5</content>
        <answer1>4</answer1>
        <answer2>1</answer2>
        <answer3>2</answer3>
        <answer4>7</answer4>
        <correctAnswer>4</correctAnswer>
    </question>
    <question>
        <content>2+5</content>
        <answer1>4</answer1>
        <answer2>1</answer2>
        <answer3>2</answer3>
        <answer4>7</answer4>
        <correctAnswer>4</correctAnswer>
    </question>
</questions>
